#!/bin/sh

# Applies pagefind to the _site folder which is generated by Jekyll. Should be executed after Jekyll created that folder.
# See https://pagefind.app/

if ! command -v docker >/dev/null 2>&1; then
  echo "Error: docker command not found" >&2
  exit 127
fi

echo "Applying pagefind to Jekyll _site"

img=$(docker build -q -f Dockerfile.pagefind .) && docker run --rm -v ".:/site" -e PAGEFIND_SITE=_site  -it "$img" && docker rmi "$img"